#!/bin/bash -e

LEFT="$(realpath "$1")"
RIGHT="$(realpath "$2")"

# check $LEFT and $RIGHT are both not empty and are directories
if [ ! -d "$LEFT" ] || [ ! -d "$RIGHT" ]; then
    echo "Usage: $0 <left_directory> <right_directory>"
    exit 1
fi

pushd "$LEFT" > /dev/null
git init --quiet --initial-branch=magit-diff-tool
git add -A
git commit --quiet -m "Stage desired changes. Kill the magit buffer when done." --allow-empty
popd > /dev/null

mv "$LEFT/.git" "$RIGHT/"

BUFNAME="$(jq -n --arg dir "$RIGHT" '["jj-magit-diff-editor", $dir]' | emacs-safeclient | jq -r)"

echo "Waiting for $BUFNAME to finish..."
sleep 0.5

while [ "$(jq -n --arg buf "$BUFNAME" '["buffer-live-p", $buf]' | emacs-safeclient)" = "true" ]; do
    sleep 0.5
done

pushd "$RIGHT" > /dev/null
git checkout --quiet -- .
git clean --quiet -df
rm -rf .git
popd > /dev/null

