#!/bin/bash

set +x

if [ $# -eq 0 ] || [ "$1" = "-h" ]; then
    exec hpshare.py "$@"
fi

ALL_KEYS="$(emacs-get-gptel-api-key hpshare.oss-cn-beijing.aliyuncs.com s.z1k.dev)"

# ALL_KEYS是两行：第一行是AWS_ACCESS_KEY_ID:AWS_SECRET_ACCESS_KEY，第二行是HPSHARE_SHLINK_API_KEY
AWS_ACCESS_KEY_ID=$(echo "$ALL_KEYS" | head -n 1 | cut -d ':' -f 1)
AWS_SECRET_ACCESS_KEY=$(echo "$ALL_KEYS" | head -n 1 | cut -d ':' -f 2)
HPSHARE_SHLINK_API_KEY=$(echo "$ALL_KEYS" | tail -n 1)

export AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY
export HPSHARE_SHLINK_API_KEY

exec hpshare.py "$@"
