#!/usr/bin/env bash
function sshrc() {
    local SSHHOME=${_SCRIPT_DATA_DIR:=~}
    local SSHCOMMAND=${SSHCOMMAND:=ssh -t}
    if [ -f $SSHHOME/sshrc.conf ]; then
        local files=sshrc.conf
        if [ -d $SSHHOME/sshrc.conf.d ]; then
            files="$files sshrc.conf.d"
        fi
        SIZE=$(tar cfz - -h -C $SSHHOME $files | wc -c)
        if [ $SIZE -gt 65536 ]; then
            echo >&2 $'sshrc.conf.d and sshrc.conf files must be less than 64kb\ncurrent size: '$SIZE' bytes'
            exit 1
        fi
        # NOTE: "bash -c" is required for moshrc
        $SSHCOMMAND "$USER_HOST" $SSHARGS bash -c "true
            command -v openssl >/dev/null 2>&1 || { echo >&2 \"sshrc requires openssl to be installed on the server, but it's not. Aborting.\"; exit 1; }
            export SSHCOMMAND=\"$SSHCOMMAND\"
            export SSHUSERHOST=\"$USER_HOST\"
            export SSHPORT=\"$SSHPORT\"
            export SSHHOME=\$(mktemp -d -t .$(whoami).sshrc.XXXX)
            export SSHRCCLEANUP=\$SSHHOME
            export INSIDE_EMACS=\"$INSIDE_EMACS\"
            trap \"rm -rf \$SSHRCCLEANUP; exit\" 0
            echo \"$(cat "$0" | openssl enc -base64 -A )\" | openssl enc -base64 -d -A > \$SSHHOME/sshrc
            chmod +x \$SSHHOME/sshrc

            echo \"$( cat << 'EOF' | openssl enc -base64 -A
                if [ -r /etc/profile ]; then source /etc/profile; fi
                if [ -r ~/.bash_profile ]; then source ~/.bash_profile
                elif [ -r ~/.bash_login ]; then source ~/.bash_login
                elif [ -r ~/.profile ]; then source ~/.profile
                fi
                export PATH=$PATH:$SSHHOME
                source $SSHHOME/sshrc.conf;
EOF
                )\" | openssl enc -base64 -d -A > \$SSHHOME/sshrc.bashrc

            echo \"$( cat << 'EOF' | openssl enc -base64 -A
#!/usr/bin/env bash
                exec bash --rcfile <(echo '
                [ -r /etc/profile ] && source /etc/profile
                if [ -r ~/.bash_profile ]; then source ~/.bash_profile
                elif [ -r ~/.bash_login ]; then source ~/.bash_login
                elif [ -r ~/.profile ]; then source ~/.profile
                fi
                source '$SSHHOME'/sshrc.conf;
                export PATH=$PATH:'$SSHHOME'
                ') "$@"
EOF
                )\" | openssl enc -base64 -d -A > \$SSHHOME/bashsshrc
            chmod +x \$SSHHOME/bashsshrc

            echo \"$(tar czf - -h -C $SSHHOME $files | openssl enc -base64 -A)\" | openssl enc -base64 -d -A | tar mxzf - -C \$SSHHOME
            export SSHHOME=\$SSHHOME
            echo \"$CMDARG\" >> \$SSHHOME/sshrc.bashrc
            bash --rcfile \$SSHHOME/sshrc.bashrc
            "
    else
        echo "No such file: $SSHHOME/sshrc.conf" >&2
        exit 1
    fi
}

function sshrc_parse() {
  SSHPORT=22
  while [[ -n $1 ]]; do
    case $1 in
      -b | -c | -D | -E | -e | -F | -I | -i | -J | -L | -l | -m | -O | -o | -Q | -R | -S | -W | -w )
        SSHARGS="$SSHARGS $1 $2"; shift ;;
      -p )
        SSHPORT="$2"
        SSHARGS="$SSHARGS $1 $2"; shift ;;
      -* )
        SSHARGS="$SSHARGS $1" ;;
      *)
        if [ -z "$USER_HOST" ]; then
         USER_HOST="$1"
        else
          local SEMICOLON=$([[ "$@" = *[![:space:]]* ]] && echo '; ')
          CMDARG="$@$SEMICOLON exit"
          return;
        fi
        ;;
    esac
    shift
  done
  if [ -z $USER_HOST ]; then
    ssh $SSHARGS; exit 1;
  fi
}

command -v openssl >/dev/null 2>&1 || { echo >&2 "sshrc requires openssl to be installed locally, but it's not. Aborting."; exit 1; }
sshrc_parse "$@"
sshrc
